services:

  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile

    depends_on:
      db:
        condition: service_healthy

    networks:
      - default
      - backend

    volumes:
      - ./:/var/www/html

    ports:
      - "8000:80"

  db:
    image: mariadb:11

    restart: unless-stopped

    environment:
      MARIADB_DATABASE: mental_health_api
      MARIADB_USER: mental_health
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - default

volumes:
  mariadb_data:

networks:
  backend:
    external: true
