services:

  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile

    container_name: mental-health-api

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www/html

    networks:
      - backend

networks:
  backend:
    external: true
