services:
  mariadb:
    image: mariadb:11
    container_name: mental-health-mariadb

    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mental_health_api
      MARIADB_USER: mental_health
      MARIADB_PASSWORD: changeme

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
