name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build application
        run: docker compose up --build -d

      - name: Wait for MariaDB
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' mental-health-db)" = "healthy" ]
          do
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Install Composer dependencies
        run: docker compose exec -T app composer install --no-interaction --prefer-dist

      - name: Run Laravel Pint
        run: docker compose exec -T app ./vendor/bin/pint --test

      - name: Run PHPStan
        run: docker compose exec -T app ./vendor/bin/phpstan analyse --no-progress

      - name: Run PHPUnit with Coverage
        run: docker compose exec -T app php artisan test --coverage

      - name: Run Mutation testing
        run: docker compose exec -T app vendor/bin/infection --min-msi=95 --min-covered-msi=95

      - name: Shutdown containers
        if: always()
        run: docker compose down --volumes --remove-orphans
