name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build application
        run: docker compose up --build -d

      - name: Show container status
        run: docker compose ps

      - name: Show app logs
        run: docker compose logs app

      - name: List project files
        run: docker compose exec -T app ls -la /var/www/html

      - name: Check container
        run: |
          docker compose ps
          docker compose exec -T app pwd
          docker compose exec -T app ls -la /var/www/html

      - name: Show app logs
        if: always()
        run: docker compose logs app

      - name: Composer manually
        run: docker compose exec -T app composer install -vvv

      - name: Verify containers
        run: docker compose ps

      - name: Run Laravel Pint
        run: docker compose exec -T app ./vendor/bin/pint --test

      - name: Run PHPStan
        run: docker compose exec -T app ./vendor/bin/phpstan analyse --no-progress

      - name: Run PHPUnit with Coverage
        run: docker compose exec -T app php artisan test --coverage

      - name: Shutdown containers
        if: always()
        run: docker compose down --volumes --remove-orphans
