name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build application
        run: docker compose up --build -d

      - name: Verify containers
        run: docker compose ps

      - name: Run Laravel Pint
        run: docker compose exec -T app ./vendor/bin/pint --test

      - name: Run PHPStan
        run: docker compose exec -T app ./vendor/bin/phpstan analyse --no-progress

      - name: Run PHPUnit with Coverage
        run: docker compose exec -T app php artisan test --coverage

      - name: Shutdown containers
        if: always()
        run: docker compose down --volumes --remove-orphans
